### ISSUE TITLE
GLM 50C connect problem

### ISSUE THREAD

**Issue by Ketti1966** [philipptrenz/BOSCH-GLM-rangefinder#1]
Hi,
I used the glm50c,py for test, just slightly modified the original
 changing from GLM100 to GLM50 
and using only GLM50 for search string
adding prints to check

the result is:
/usr/bin/python3.5 /home/zoltan/PycharmProjects/MC50Boschlaser/glm50c.py
Searching for BOSCH GLM50C ...
Found BOSCH GLM50C @ 00:13:43:59:FC:1B
address:
00:13:43:59:FC:1B
Connecting to BOSCH GLM50C failed connect(self)
Could not connect to BOSCH GLM50C

Process finished with exit code 0

the address is the same if I connect manually, as can be seen on the picture.

what can be the solution?
best regards
Zoltan

![connected](https://user-images.githubusercontent.com/43019829/48483091-73ef7980-e84d-11e8-95f5-3dd4a3491a3c.jpg)

[glm50c.txt](https://github.com/philipptrenz/BOSCH-GLM-rangefinder/files/2580710/glm50c.txt)

**Comment by philipptrenz** [comment]
Hi @Ketti1966,

the MAC seems to be fine, so something went wrong while trying to connect. I just tested on Windows, so it may be related to Ubuntu; Bluetooth is pretty OS dependent. 
I think the way to go is to enable debug messages, not sure how it works with Ubuntu. [This](https://stackoverflow.com/questions/37003147/i-want-to-enable-debug-messages-on-bluez) may be helpful for you.
If you post your debug log I'll try to help with identifying the fault.

**Comment by Ketti1966** [comment]
Hi @philipptrenz 

the result is below, but seems no meaning for me unfortunately
the 十一  means 11

```
zoltan@zoltanpc:/etc/systemd/system/bluetooth.target.wants$ journalctl --unit=bluetooth -f
-- Logs begin at 四 2018-11-15 15:53:42 CST. --
十一 15 20:10:41 zoltanpc bluetoothd[26404]: src/device.c:device_svc_resolved() /org/bluez/hci0/dev_00_13_43_59_FC_1B err 0
十一 15 20:10:45 zoltanpc bluetoothd[26404]: src/adapter.c:dev_disconnected() Device 00:13:43:59:FC:1B disconnected, reason 2
十一 15 20:10:45 zoltanpc bluetoothd[26404]: src/adapter.c:adapter_remove_connection()
十一 15 20:10:45 zoltanpc bluetoothd[26404]: src/adapter.c:adapter_remove_connection() Removing temporary device /org/bluez/hci0/dev_00_13_43_59_FC_1B
十一 15 20:10:45 zoltanpc bluetoothd[26404]: src/device.c:device_remove() Removing device /org/bluez/hci0/dev_00_13_43_59_FC_1B
十一 15 20:10:45 zoltanpc bluetoothd[26404]: src/device.c:btd_device_unref() Freeing device /org/bluez/hci0/dev_00_13_43_59_FC_1B
十一 15 20:10:45 zoltanpc bluetoothd[26404]: src/device.c:device_free() 0x562f6aa27880
十一 15 20:10:45 zoltanpc bluetoothd[26404]: plugins/policy.c:disconnect_cb() reason 2
十一 15 20:10:45 zoltanpc bluetoothd[26404]: src/adapter.c:bonding_attempt_complete() hci0 bdaddr 00:13:43:59:FC:1B type 0 status 0xe
十一 15 20:10:45 zoltanpc bluetoothd[26404]: src/adapter.c:resume_discovery()
```

**Comment by philipptrenz** [comment]
@cgommel created an improved fork with support for the GLM50C. As long as it is not merged into my repository please check out [his fork](https://github.com/cgommel/BOSCH-GLM-rangefinder).

**Comment by MiliStefanos** [comment]
What about connection with Windows10 ? I am trying to connect GLM50C via [Bluetooth] with Windows apps and VS projects but always seems to be connected and then connection is lost. I tried 3 windows Apps (ArCADia, siteMaster CAD, GLM transfer software) and 2 projects ( python [here](https://medium.com/analytics-vidhya/how-to-use-connect-bluetooth-in-python-from-scartch-to-bosch-glm-50-c-in-window-e75d8206fab4),  and C# [here](https://github.com/Scarfsail/BoschGLM50) )but the same behavior. The GLM seems the connection symbol and after a while the connection is lost.  However, the GLM50c has no problem with Android Apps. 

Does anyone have face similar problems? Do you have any idea how this can be fixed?
