### ISSUE TITLE
GLM50 Fail to connect

### ISSUE THREAD

**Issue by JoaoCH** [philipptrenz/BOSCH-GLM-rangefinder#11]
good afternoon,

I'm using MAC OS.

I can find the GLM50C but I cannot connect.
I even tried a fork that you had indicated in an issue that is closed and doesn't work.

can you help?

Searching for BOSCH GLM50C
Found BOSCH GLM50C @ b'00:13:43:85:21:53'
Trying to connect with GLM50C
Can't connect with GLM50C
Could not connect to GLM50C

**Comment by MiliStefanos** [comment]
I face the same problem with Windows 10. I can find the GLM50C but I cannot connect.  
I have also tried to connect with windows Apps (ArCADia CAD software, sitemaster CAD software, GLM transfer software) but the same results. 

Any idea?

**Comment by greenbird4** [comment]
On LINUX Ubuntu 22.04.2 LTS:  After a short coupling, it stays disconnect.

How it's possible to connect and transfer the data into LibreOffice?

$ bluetoothctl info 00:13:43:BE:5A:DF
Device 00:13:43:BE:5A:DF (public)
	Name: Bosch GLM50C x2854
	Alias: Bosch GLM50C x2854
	Paired: yes
	Trusted: yes
	Blocked: no
	Connected: no
	LegacyPairing: no
	UUID: Serial Port     (00001101-0000-1000-8000-00805f9b34fb)

**Comment by lefuturgeometre-france** [comment]
Bonjour, je rencontre exactement le même problème sur Windows 11, en revanche le télémètre se connecte bien à GLM Transfer mais pas avec le programme python.

Trying to connect with GLM50C
Connection Error. Can't connect with GLM50C
Could not connect to GLM50C

Quel serait le problème ?
