### ISSUE TITLE
"ERROR: bosch-glm-rangefinder 0.0 has requirement PyBluez==0.22, but you'll have pybluez 0.23 which is incompatible."

### ISSUE THREAD

**Issue by sanderjo** [philipptrenz/BOSCH-GLM-rangefinder#12]
sudo pip3 install pybluez on Ubuntu 20.04 results in

`ERROR: bosch-glm-rangefinder 0.0 has requirement PyBluez==0.22, but you'll have pybluez 0.23 which is incompatible.
`

Is pybluez 0.23 really incompatible?

**Comment by sanderjo** [comment]
workaround for now:

`sudo pip3 install pybluez==0.22`

**Comment by oberbichler** [comment]
Hi!
To avoid this problem I replace `pybluez` with `PyQt6.QtBluetooth`. [Here you can find the code](https://github.com/oberbichler/bosch-plr).
