### ISSUE TITLE
help needed pairing Ubuntu and/or Windows with Bosch PLR 30 C

### ISSUE THREAD

**Issue by sanderjo** [philipptrenz/BOSCH-GLM-rangefinder#14]
After pressing the Bluetooh key on the Bosch PLR 30 C, the bluetooth item appears in the Bosch PLR 30 C's screen, and Ubuntu does discover the Bosch PLR 30 C. In Ubuntu, when I click on Connect, Ubuntu says:

![image](https://user-images.githubusercontent.com/1273502/101954126-dd444100-3bfb-11eb-8357-d84a724520b4.png)

After Confirming that ... still Disconnected. 

Tip how to get the Bluetooth connection working?

![image](https://user-images.githubusercontent.com/1273502/101954346-314f2580-3bfc-11eb-8b41-8d369916e7d5.png)

![image](https://user-images.githubusercontent.com/1273502/101954551-94d95300-3bfc-11eb-8063-6621ecf6afb6.png)

**Comment by sanderjo** [comment]
I activated logging like described https://stackoverflow.com/a/38462866/1492917 ... but easy grep -i  "bosch" or "plr" does not reveal anything

**Comment by sanderjo** [comment]
... it neither works from Windows:

Windows does see the PLR30C, it connects, the PLR30C shows an extra symbol to the bluetooth symbol ... and then nothing

![image](https://user-images.githubusercontent.com/1273502/101993561-e98fd300-3cbb-11eb-9de5-8a29b40330f9.png)

**Comment by sanderjo** [comment]
FWIW: I can connect from Android to the PLR30C (so Bluetooth is working), but that is besides the point as I can't run the python script on Android.

Is the Bosch PLR30C actively refusing connections from PC's?

**Comment by petrisch** [comment]
Not shure if thats any helpfull here.
What I discovered is, that it works at least better, if I don't try to connect from the PC, but rather let the script do the connection, and just accept it from Ubuntu. I have only GLM50C though.
