### ISSUE TITLE
GLM50C Connect Problem 

### ISSUE THREAD

**Issue by PrathamBumb** [philipptrenz/BOSCH-GLM-rangefinder#2]
I too tried with glm50c. Scripts says could not connect to glm50c but the scripts is able to find the device plz find any solution to it 
Best Regards
Pratham Bumb

**Comment by philipptrenz** [comment]
@cgommel created an improved fork with support for the GLM50C. As long as it is not merged into my repository please check out [his fork](https://github.com/cgommel/BOSCH-GLM-rangefinder).

**Comment by PrathamBumb** [comment]
Thanks You
Really Help Me Now Script Works Well On Windows.
Will It Works On Raspberry Pi ?

**Comment by philipptrenz** [comment]
@cgommel is also working on that, see [here](https://github.com/philipptrenz/BOSCH-GLM-rangefinder/issues/3#issuecomment-451601200)

**Comment by cgommel** [comment]
in my [fork](https://github.com/cgommel/BOSCH-GLM-rangefinder) it works on a raspberry pi zero and a GLM 50C. Will be merged here later on.

**Comment by PrathamBumb** [comment]
Ok
Can you tell me the steps to install Bluetooth lib on raspberry pi zero

**Comment by cgommel** [comment]
Was easy for me. just did 

`sudo pip install pybluez`

and then it worked.

It was way more pain in the ass to achieve this in windows.

> Ok Can you tell me the steps to install Bluetooth lib on raspberry pi zero
> […](#)

**Comment by PrathamBumb** [comment]
Are You Using Raspbian Or NOOBS ?

**Comment by cgommel** [comment]
Raspbian on a Raspberry Pi Zero W

**Comment by PrathamBumb** [comment]
so after fresh install of Raspbian will this commands work ?

**Comment by PrathamBumb** [comment]
Not able to install pybluez on raspberry pi zero facing problem build fail

**Comment by philipptrenz** [comment]
The Raspberry Pi Zero (not W) does not have a Bluetooth interface. Therefore, it inevitably fails.

**Comment by PrathamBumb** [comment]
Hey Hi Man The Code Is Now Working Like A Charm After Proper Installation
On My Raspberry Pi
So I Am Having Some Problem In This Following Case :
so i have connected successfully to the glm and able to send the send the
command and receive the distance val OK but in case while the glm is
connected to the Bluetooth and i manually turn of the glm the code is in
the loop of listen for the "m" right so when we send the command the
program get break. so is there any way to check the real time status of
Bluetooth communication and then send the command.

Thank You,
Regards,
Pratham Bumb
