### ISSUE TITLE
Command help

### ISSUE THREAD

**Issue by madeleinefrancis** [philipptrenz/BOSCH-GLM-rangefinder#4]
Hi there,

I'm wondering what the listen command is supposed to do as I'm currently getting some strange results.. 
Also if you have any leads on where to find other commands from the protocol it would be of great help! 

Thanks :)

**Comment by redcodey** [comment]
hi @madeleinefrancis  @philipptrenz 
Its quite long but no one answer this. I tried to look up for the command list also but couldnt find them.
If you already found them, can you share. thank you!

**Comment by vitaliykoziy** [comment]
hi @madeleinefrancis @philipptrenz @redcodey 
Has anyone found the list of commands ? I couldn't find them also :(

**Comment by redcodey** [comment]
hi @vitaliykoziy ,
the only legal way is contact BOSCH and register and sign the developer contract.
They will provide you the command.
I got the command but can not share due to the privacy.

**Comment by vitaliykoziy** [comment]
@redcodey  thank you for answering
